M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Sat May 13 22:43:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-13T22:43:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
%
G90
G05
T1
X12.7Y55.448
X72.555Y55.448
X72.555Y2.565
T0
M30
