name: Generate release files

permissions:
  contents: write
on:
  push:
    tags:
      - "Release_**"
      - "Rev**"
      - "Proto**"
      - "proto**"
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip Gerbers
        run: zip -r Gerbers.zip Gerbers
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            Docs/Schematic.pdf
            Docs/*-ibom.html
            Gerbers.zip
            Gerbers/*_bom_jlc.csv
            Gerbers/*_cpl_jlc.csv
            Binary/*.jed
            Software/cflash/cflash
