name: Generate release files

permissions:
  contents: write
on:
  push:
    tags:
      - "Release_**"
      - "Rev**"
      - "Proto**"
      - "proto**"
  workflow_dispatch:

jobs:
  make_software:
    runs-on: ubuntu-latest
    container: liv2/amiga-gcc-amitools
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Addram
        run: make
        working-directory: Software/addram

      - name: Build bootrom
        run: make
        working-directory: Software/bootrom

      - name: Build cflash
        run: make
        working-directory: Software/cflash

      - name: Package software
        run: |
          export TMPDIR=/tmp/cider_wd
          export ARTIFACTDIR=${PWD}/artifacts
          mkdir -p ${TMPDIR}
          mkdir -p ${ARTIFACTDIR}
          rm -rf ${TMPDIR}/*
          cp Software/addram/addram ${TMPDIR}
          cp Software/bootrom/bootrom ${TMPDIR}
          cp Software/cflash/cflash ${TMPDIR}
          cd ${TMPDIR}
          xdftool ${ARTIFACTDIR}/CIDER-Software.adf format CIDER + write addram + write bootrom + write cflash
          lha -c ${ARTIFACTDIR}/CIDER-Software.lha *

      - uses: actions/upload-artifact@master
        with:
          name: software
          path: artifacts/*

  kicad_outputs:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:ki6.0.7_Debian
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Generate outputs
        run: kibot -c kibot/release.kibot.yaml
        working-directory: Kicad
      - uses: actions/upload-artifact@master
        with:
          name: Gerbers
          path: Gerbers/*
      - uses: actions/upload-artifact@master
        with:
          name: kicad
          path: |
            Docs/*.pdf
            Docs/*.html
            Docs/*.png
            Gerbers/*.csv

  draft_release:
    runs-on: ubuntu-latest
    needs:
      - make_software
      - kicad_outputs

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Zip Gerbers
        run: zip -r Gerbers.zip Gerbers
        working-directory: artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            Binary/*.jed
            artifacts/Gerbers.zip
            artifacts/software/**/*
            artifacts/kicad/**/*
